stages:
  - qa
  - build
  - deploy

variables:
  NODE_ENV: production
  IMAGE: hub.sekhnet.ra/budget-web-v2
  NAMESPACE: budget

lint:
  image: node
  stage: qa
  cache:
    paths:
      - ./node_modules/
  script:
    - npm install eslint
    - ./scripts/lint.sh

build-prod:
  image: docker:latest
  stage: build
  before_script: []
  services: []
  only:
    - main
  script:
    - docker pull $IMAGE:latest || true
    - docker build -t "$IMAGE:latest" -t "$IMAGE:$CI_COMMIT_SHA" --cache-from $IMAGE:latest . 
    - docker image push --all-tags "$IMAGE"


build-dev:
  image: docker:latest
  stage: build
  before_script: []
  services: []
  only:
    - dev
  script:
    - docker pull $IMAGE:latest || true
    - docker build -t "$IMAGE:dev" -t "$IMAGE:$CI_COMMIT_SHA" --cache-from $IMAGE:latest . 
    - docker image push --all-tags "$IMAGE"

deploy-staging:
  stage: deploy
  before_script: []
  services: []
  image: dtzar/helm-kubectl
  only:
    #- dev
    - this-step-is-currently-disabled
  script:
    - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@git.sekhnet.ra/sekhnet/applications/budget/budget-helm.git
    - ./budget-helm/scripts/setup-ci-service-account.sh $STAGING_TOKEN $CA
    - helm upgrade -n $NAMESPACE-staging $NAMESPACE-staging ./budget-helm --set=web.image.tag="$CI_COMMIT_SHA" --reuse-values --atomic

deploy-prod:
  stage: deploy
  before_script: []
  services: []
  image: dtzar/helm-kubectl
  only:
    #- main
    #- dev
    - this-step-is-currently-disabled
  script:
    - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@git.sekhnet.ra/sekhnet/applications/budget/budget-helm.git
    - ./budget-helm/scripts/setup-ci-service-account.sh $PROD_TOKEN $CA
    - helm upgrade -n $NAMESPACE $NAMESPACE ./budget-helm --set=web.image.tag="$CI_COMMIT_SHA" --reuse-values --atomic
