export const SET_AUTH_TOKEN_SUCCESS = "SET_AUTH_TOKEN_SUCCESS";
export const CLEAR_AUTH_TOKEN = "CLEAR_AUTH_TOKEN";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const LOAD_BUDGETS_SUCCESS = "LOAD_BUDGETS_SUCCESS";
export const UPDATE_BUDGET_SUCCESS = "UPDATE_BUDGET_SUCCESS";

export const LOAD_TAGS_SUCCESS = "LOAD_TAGS_SUCCESS";
export const LOAD_TRANSACTIONS_SUCCESS = "LOAD_TRANSACTIONS_SUCCESS";

export const LOAD_USER_INFO_SUCCESS = "LOAD_USER_INFO_SUCCESS";
