import { ROUTES } from "../../app/AppRoutes";

export const links = [
  ROUTES.DASHBOARD,
  ROUTES.TRANSACTIONS_ADD,
  ROUTES.TRANSACTIONS_LIST,
  ROUTES.BUDGET_LIST,
  ROUTES.TRANSACTION_REPORT,
  ROUTES.SETTINGS,
];
