import { ROUTES } from "../../app/AppRoutes";

export const links = [
  ROUTES.DASHBOARD,
  ROUTES.TRANSACTIONS_ADD,
  ROUTES.TRANSACTIONS_LIST,
  ROUTES.BUDGET_LIST,
  ROUTES.QUERY,
  ROUTES.SETTINGS,
];

export const DRAWER_WIDTH = 288;
